# Generated by Django 4.2.11 on 2024-04-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_alter_account_id_alter_bank_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="name",
            field=models.CharField(default="new", max_length=20),
        ),
    ]
