# Generated by Django 4.2.11 on 2024-04-25 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0003_bank_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="bank.bank"
            ),
        ),
    ]
