# Generated by Django 4.2.11 on 2024-04-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_accountdetail_accountmaster_alter_account_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDetail',
        ),
        migrations.AddField(
            model_name='accountmaster',
            name='name',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='accountmaster',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accountmaster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
