# Generated by Django 4.2.11 on 2024-04-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_delete_accountdetail_accountmaster_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
    ]
