# Generated by Django 4.2.11 on 2024-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0010_rename_accountmaster_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="witdhdraw",
            field=models.BooleanField(default=False),
        ),
    ]
