# Generated by Django 4.2.11 on 2024-04-27 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0011_account_witdhdraw"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="witdhdraw",
            new_name="withdraw",
        ),
    ]
